#!/bin/sh

case $1 in
start)
	echo "starting cec"
	if [ ! `grep 'hdmicec.enabled=false' /etc/enigma2/settings` ];then
		insmod /lib/modules/cec.ko
	fi

	exit 0

	;;
stop)
	echo "stopping cec... error, cec cannot be stopped, aborting"
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

